Repository Lion-Craft/Tinyinfo, pull requests merged in 2023-10, with the labels that each got.

#6 Added Motherboard information
  Tinyinfo/MainWindow.cs
Labels: enhancement

#8 Added info load on startup
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#10 Added Always on Top checkbox
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#15 Update GPU branch
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#16 5 graphics carddispaly adapter info
  Tinyinfo/MainWindow.cs
Labels: enhancement

#18 17 simplify load code
  Tinyinfo/MainWindow.cs
Labels: enhancement

#20 Fixed graphics info not loading
  Tinyinfo/MainWindow.cs
Labels: bug

#21 Update Menubar dev branch
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#22 Fix resolution
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/Program.cs
Labels: bug, enhancement

#27 3 battery info
  Tinyinfo/MainWindow.cs
Labels: bug, enhancement

#29 Fixed RaceOnRCWCleanup Exception
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: bug

#32 Removed unreachable code
  Tinyinfo/MainWindow.cs
Labels: bug

#36 30 battery info incorrect description
  Tinyinfo/MainWindow.cs
Labels: bug

#38 37 nullrefrenceexception when exiting program without continuously updating
  Tinyinfo/MainWindow.cs
Labels: bug

#40 39 improve form object naming
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/MainWindow.resx
  Tinyinfo/SettingsWindow.Designer.cs
  Tinyinfo/SettingsWindow.cs
Labels: documentation, enhancement

#41 Added Refresh menubar item
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#43 1 drive info
  Tinyinfo/MainWindow.cs
Labels: enhancement

#45 Fixed Battery section title
  Tinyinfo/MainWindow.cs
Labels: bug

#47 Section titles no longer being output from within foreach
  Tinyinfo/MainWindow.cs
Labels: bug

#49 Fixed Memory section whitespace
  Tinyinfo/MainWindow.cs
Labels: bug

#50 28 network adapter info
  Tinyinfo/MainWindow.cs
Labels: enhancement

#52 Version 2.0
  Tinyinfo.sln
  Tinyinfo/Properties/AssemblyInfo.cs
  Tinyinfo/Tinyinfo.csproj
Labels: enhancement

#54 Update Readme from master
  README.md
Labels: enhancement

#56 Added File dropdown and Export item to export output text to file
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#59 Add Exit menubar item
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement, ui/ux

#61 Update README.md with more info
  README.md
Labels: documentation, enhancement

#65 Remove play/pause button
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: bug

#66 Add Logo
  .gitignore
  Logo/Logo.blend
  Logo/logo.ico
  Logo/logo.png
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.resx
  Tinyinfo/Tinyinfo.csproj
  Tinyinfo/logo.ico
Labels: enhancement

#67 Update .gitignore
  .gitignore
Labels: bug

#68 Added button to export as JSON :)
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/Tinyinfo.csproj
  Tinyinfo/packages.config
Labels: enhancement

#70 Organized MainWindow.cs
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement

#72 Update Keyboard Shortcut branch
  .gitignore
  Logo/Logo.blend
  Logo/logo.ico
  Logo/logo.png
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/MainWindow.resx
  Tinyinfo/Tinyinfo.csproj
  Tinyinfo/logo.ico
  Tinyinfo/packages.config
Labels: enhancement

#73 62 menubar keyboard shortcuts
  Tinyinfo/MainWindow.Designer.cs
Labels: bug

#74 Fixed Formatting
  Tinyinfo/MainWindow.cs
Labels: bug

#76 69 detect if no battery is present
  Tinyinfo/MainWindow.cs
Labels: enhancement

#81 Added missing file types and default file name
  Tinyinfo/MainWindow.cs
Labels: bug

#82 Added SaveFileDialog titles
  Tinyinfo/MainWindow.cs
Labels: bug

#88 Changed StartPosition to CenterParent
  Tinyinfo/SettingsWindow.Designer.cs
Labels: bug

#93 Update Preview image
  Tinyinfo/Preview.png
Labels: enhancement

#94 Update README
  README.md
Labels: enhancement

#98 33 redo UI
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
Labels: enhancement, ui/ux

#100 2 cpu update thread
  Tinyinfo/MainWindow.cs
  Tinyinfo/SettingsWindow.Designer.cs
  Tinyinfo/SettingsWindow.cs
Labels: enhancement

#102 Add Logo to README.md
  README.md
Labels: enhancement

#103 Add different Splashes
  Logo/Splash.xcf
  Logo/splash_dark.png
  Logo/splash_transparent.png
  Logo/splash_transparent_white.png
Labels: enhancement, ui/ux

#104 96 use nvapiwrapper for nvidia gpu information
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/Tinyinfo.csproj
Labels: enhancement

#105 Changed Dark Theme from black to gray
  Tinyinfo/MainWindow.cs
  Tinyinfo/SettingsWindow.cs
Labels: enhancement, ui/ux

#107 106 redo settings window
  Tinyinfo/SettingsWindow.Designer.cs
  Tinyinfo/SettingsWindow.cs
  Tinyinfo/SettingsWindow.resx
  Tinyinfo/Splash.Designer.cs
  Tinyinfo/Splash.resx
Labels: enhancement, ui/ux

#113 90 font selection
  Tinyinfo/MainWindow.Designer.cs
  Tinyinfo/MainWindow.cs
  Tinyinfo/SettingsWindow.Designer.cs
  Tinyinfo/SettingsWindow.cs
Labels: enhancement

#114 108 splash theme
  Tinyinfo/MainWindow.cs
  Tinyinfo/SettingsWindow.Designer.cs
  Tinyinfo/SettingsWindow.cs
  Tinyinfo/Splash.Designer.cs
  Tinyinfo/Splash.cs
  Tinyinfo/Tinyinfo.csproj
  Tinyinfo/img/splash/splash.png
  Tinyinfo/img/splash/splash_dark.png
  Tinyinfo/img/splash/splash_transparent.png
  Tinyinfo/img/splash/splash_transparent_white.png
Labels: bug, enhancement, ui/ux
